language: python
sudo: required
dist: xenial
python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install .
script: pytest
deploy:
  provider: pypi
  user:
    secure: JT7b8ZTL6yRGWyFoJtP5IEOXjq4nphsryRjYjQVi+XtPLIwbvlX2ZdnH0H7k7EFR8mYUaIyRuGAnuoMOwiscC91m7qukvuOgFSAKsUcuJR7aTTbDZdWM/WutU8Zk9pC5vFzduL2eIYYTufwvFlJxqLzyMI6ebQH7izwfMLSVfaYwm4u7Ob1qa7XMqcwxx4ga2o4Z50QXJKFOnc7LaYpQWAv8rTqgxAvCjQQlSr8GRm1SHntMIWiDW3KOUuoe0G+0/HjZgeqZWVnf8tipGd1eHpn2vNvozvBFSo2upPyvbqKWk+XU4tBCPrrP592UTfF9gqL0MpATzCQ4TUimAl2Cr8+zuYGPmzl32uuROX/3U4lg9jJXFXE8IY1lPG4tLxr2Gkc1RrTBSFoL+9faqHleAxepxLBhceR6fV1g1PSb8O8+gGVt8g8SpZCz/zsfbV+i9ukL+fjlQHK6hOLZRJY4ixSy7XTl+sxuApc4/au9Z8kt39cIFe6zlqLz+1gLbwXIf2fQ9nHPYFE0P/nG03sbflmdL2zxH9jumBF1jJjSQXrKRcpknyOvG5RLAO95tFpAO8Ovn92twjd82ugPHlPCYEeOtxYorWDvgoQn00f/roIdXi0bdEccu05zdguJiUu6ziwheLVvoMsXHfaW0+tzwWLhB2fI3lxhEsRaht3IqLw=
  distributions: sdist bdist_wheel
  pasword:
    secure: IDZh3c3tdLBKr2wkN/BGZwS5G2+UWhy39W2M/feCZsciy0rhH81s0Vqe4Eh5+sIRVtf+kcdz/+SV8o7+Qk3OCBfclPiSPukSj2ofY06zKhlfhAvcXXzhmnEd50nCS3rgV4SG1xiCEVdYTod5/9De9GgRS3KKZjo4F2y+LIBCnLTbStY73XVGAwvYzchQNVXY0pE/rxc2IZUaJ7+0Ti3nMwhN9Gsop9xutMqujwou2s9GCD8yR6Wp7mrPVUfmWgczyt2bE0PU3sg+tQn6kd/F9CMh5jTZA3dBxyquQKgRy/kcmidc9nOjG3uUGaRqt2oVfCz0cznRpxQZbliILtt7X8xX4FLAmi5mXh6R5wLjxAUNl78RREJWgPPEGU7uJuWn7ecNXzwfMKuIbDavcXHiGd9MVRB2mSm7KpUB3dVULrHDTy0ngHihSTa5uGNdH3LTAjWhRzThFHsW1CXP0HiYZJj2lBj23HPn7cj4MUZWsSN2I5a3QQNHnq+lhxLntKeVz2Zfv0uD+pM/Zo1GJEMuS7p+A3xEWzajhnj51FpzZw+GCYnHuOLrAPv9AeNsEmpSXlXetGhmxSI5A87dqgNK5u2Ggy/yFT6boLcg9lJrfbd/RcYIb/uGeJfsgJ3Sg8dBUpECemOKG7YQ922hOyrAw13vHyq9jp7CYRRa8xjzy6s=
  on:
    tags: true