language: python
sudo: required
dist: xenial
python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install .
script: pytest
env:
  - TRAVIS=true
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user:
    secure: DpL+MC/wm5yxzFDkf5ZMQHNSx+X76EFMhdyXYQC+/pJaOFgpsKijvVyFW0VKtyJ56Vq7nVl59M5FKI3LpcBTmu64of77dcRCmq49c1ETKRWG0g+NTiVHEyuPAooso03RTzADwPCdEYXvvNewu+Mx1qTDdrnpnJs3ncjD7VOKWrvZSeRjQsG8mdAFatZ+KHRCD2PlOsdD3b8Hig8cfxU5cJjLHgCchkpY8V1BqdG7OcE3g8rP1n6YknVgr+6H0pRLNezNDkbHbJ/FzeOya4V9aod6+Y1fW1RRz2QwXYIU155d+entIo5WsEs5xiBRnhMFaX3NHs8SrUkkCGqrUFz+sYY9wRKJj7zVcA53ZGt7sdiBQy93mL6ZD8zrkmSx7Ze25N7qJYwA0k8gW24VHd6U680ECmHM/RdFd0GAO/Vh2khMaX9mz/tar2TySeiA0UsyIbXfrbusZ62YYn7D1ywDJAV26Iik5BcBdgdsb733Lc6A+JPvD2kWSMhDg6xTWrlqwhFvFStU3KA5urFg55HapXZhEsIlOto45BZaRMNG+PfX7/5VeLPl7/oKWLgC4qfSyFk+0Aded4PZ2CvbtwTPCuiKgJiUjZVmzXAqgXgfbFpfAEipiuNE9oqRTM3yNxlDr9fssy5YZQqiZ27qwiviqQes3tBBPceRkHLXdMSZHE4=
  password:
    secure: kXIh5fUXfZKTvlMoEVFlVhwk6NRrcI7Rb6YCKs1qH0J75TG00/xEr/jvjhWhxsOJZ/Mx/7E889iz1cww8qQMkaD8Oub7u8Y115BntLxC9lKx11OocyzrluVpkGmESmyIbvAkHh5jsCVn8Yt2EBARYynZDJDjDoAKHKMuxR6H2+TN2RS7XSY5qLVDmAHyQoVajdApYfg0EIYRK9hYmYQoS8YfphQZJyBiz+2yWtTNZjjPW2eruwzAqXvEVJroZurFA+mNx9HaKC6pdkHFYYL+NBFes2Ff907xbfaE6jYqoN0gbt83UOu+2e0IiSxfQuTY56Fedh9Nchc910+mBGZ0zwzY4ibOQRKMXEFL5aMP2K5eZuDQMevj6HHHm56RTfhQjp5wyITzzMfhWMIZy6xM1wJVOMQIZuw7qL9iUktKirlWImcpmvgHKzkiVX3CwOaZFiPDAqe2Dbbr7RoxKtbv3/LqtRd+cFgIwO5Cte0vUXizWCdOMi6hWU/OvXMRnqH9FsYY4BlLADw2DK7umkJITO8suoN8tkmEa3wqZPCtZk8RRFgvOaaMd3bKJgejk2Z7kvvPeO0MK3o7VWs69FXvtUVQoKLO2navUI6VVxDCWSHS83EXRYktgAWHvAulqdqLIs8TjaXzIKPgqHw192AsRuFl9N9op7l4dm7GWKunTqM=
  on:
    tags: true
after_success:
  - git config --global user.name "semantic-release (via TravisCI)"
  - git config --global user.email "semantic-release@travis"
  - pip install python-semantic-release
  - semantic-release publish
