language: python
sudo: required
dist: xenial
python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install .
script: pytest
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
  on:
    tags: true

after_success:
  - git config --global user.name "semantic-release (via TravisCI)"
  - git config --global user.email "semantic-release@travis"
  - pip install python-semantic-release
  - semantic-release publish
